# Generated by Django 3.1.4 on 2020-12-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='demanda',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='celular',
            field=models.CharField(max_length=150, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='cep',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=120, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=20, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='telefone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
