# Generated by Django 3.1.4 on 2020-12-09 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201209_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='rua',
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='registro ativo')),
                ('cep', models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP')),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=20, null=True, verbose_name='País')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=120, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade')),
                ('rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=120, null=True, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.demanda')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
